In [ ]:
Profesor: Alvaro Javier Cangrejo

# NumPy ndarray
- NumPy (__Num__ erical __Py__ thon) es la de facto librería estándar para análisis numérico en Python
- Estructura de datos multidimensional eficiente (escrita en C): ndarray
- Colección de funciones para álgebra lineal, estadística descriptiva
- Ayuda al procesamiento de datos (np.where)

In [ ]:
# importar libreria
import numpy as np

## Formas de crear ndarrays

* un ndarrays(N-dimensional array) es similar a una lista o matriz.

In [ ]:
array = np.array([[2, 71, 0, 34], [2, 171, -35, 34]])  # 2D
print(array)

[[  2  71   0  34]
 [  2 171 -35  34]]


In [ ]:
shopping_list = [["onions", "carrots", "celery"], ["apples", "oranges", "grapes"]]  # 2D
array = np.array(shopping_list)  # convertir una lista en una ndarray
print(array)
print(type(array))

[['onions' 'carrots' 'celery']
 ['apples' 'oranges' 'grapes']]
<class 'numpy.ndarray'>


In [ ]:
print(np.array([100, 10, 1]))  # array a partir de una lista
print(np.arange(2, 10, 2.1))  # array a partir de una secuencia(range) 1D

[100  10   1]
[2.  4.1 6.2 8.3]


In [ ]:
# Generar arrays con valores fijos
print(np.zeros(2))  # 1D
print(np.ones((2, 2)))  # matrix 2x2
print(
    np.empty((2, 2, 2))
)  # matrix 2x2x2 (dos bloque 2x2), no inicializados: es decir valores aleatorios residuales en memoria
print(np.full((5, 2), 3))  # matrix 5x2 (dimensión) --> 3 valor que compone la matriz
print(np.eye(3))  # matrix identity

[0. 0.]
[[1. 1.]
 [1. 1.]]
[[[9.88e-324 3.51e-322]
  [0.00e+000 1.68e-322]]

 [[9.88e-324 8.45e-322]
  [      nan 1.68e-322]]]
[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Obtener información sobre ndarray

In [ ]:
my_ndarray = np.array([2, 71, 0, 34])
print(my_ndarray)

[ 2 71  0 34]


In [ ]:
print(my_ndarray.argmax())  # índice del valor más alto
print(np.amax(my_ndarray))

print(my_ndarray.argmin())  # índice del valor más bajo
print(np.amin(my_ndarray))

print(my_ndarray.nonzero())  # retorna los índices de los elementos distintos a 0

1
71
2
0
(array([0, 1, 3]),)


In [ ]:
my_ndarray = np.full(
    (5, 2, 2), -3
)  # matrix 5x2 (5 bloques, 2 filas por bloques y 2 columnas por fila) array tridimensional
print(my_ndarray)

print(my_ndarray.size)  # número de elementos
print(my_ndarray.shape)  # dimensiones
print(my_ndarray.ndim)  # número de dimensiones

[[[-3 -3]
  [-3 -3]]

 [[-3 -3]
  [-3 -3]]

 [[-3 -3]
  [-3 -3]]

 [[-3 -3]
  [-3 -3]]

 [[-3 -3]
  [-3 -3]]]
20
(5, 2, 2)
3


In [ ]:
my_ndarray = np.array([2, 71, 0, 34])  ## array (1D)

print(my_ndarray.size)  # número de elementos
print(my_ndarray.shape)  # dimensiones
print(my_ndarray.ndim)  # número de dimensiones

4
(4,)
1


#### Redimensionar los datos

In [ ]:
my_ndarray = np.array(
    [[10, 71, 21, 19, 213, 412, 111, 98]]
)  # matrix 1x8 como es una matrix lleva [[ ]] (2D), un array simple []
print(my_ndarray)
print(my_ndarray.shape)
print(my_ndarray.ndim)

[[ 10  71  21  19 213 412 111  98]]
(1, 8)
2


In [ ]:
new_dims = my_ndarray.reshape(2, 4)  # cambiar las dimensiones a 2x4
print(new_dims)

[[ 10  71  21  19]
 [213 412 111  98]]


In [ ]:
new_dims = my_ndarray.reshape(4, 2)  # cambiar las dimensiones a 4x2
print(new_dims)

[[ 10  71]
 [ 21  19]
 [213 412]
 [111  98]]


In [ ]:
# reducir a 1D
new_dims = np.arange(9).reshape(3, 3)
print(new_dims)
print(
    new_dims.flatten()
)  # El método .flatten() convierte un array de cualquier número de dimensiones en un vector unidimensional (1D).

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


## Manipulación de ndarrays

In [ ]:
# Cambiar ejes
new_dims = np.arange(16).reshape(8, 2)
print(new_dims)
print(new_dims.swapaxes(0, 1))  # Intercambia filas (axis=0) con columnas (axis=1)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[[ 0  2  4  6  8 10 12 14]
 [ 1  3  5  7  9 11 13 15]]


In [ ]:
# Flip
new_dims = np.arange(16).reshape(4, 4)
print(new_dims)
print(np.flip(new_dims))  # np.flip(new_dims): Invierte la matriz new_dims
# a lo largo de todos los ejes, resultando en una matriz donde los elementos están en el orden inverso.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [ ]:
# ordenar
array1 = np.array([10, 2, 9, 17])
array1.sort()
print(array1)

[ 2  9 10 17]


In [ ]:
# Juntar dos arrays
a1 = [0, 0, 0, 0, 0, 0]
a2 = [1, 1, 1, 1, 1, 1]

print(np.hstack((a1, a2)))  # una al lado de la otra
print(np.hstack((a1, a2)).shape)

print(np.vstack((a1, a2)))  # una encima de la otra
print(np.vstack((a1, a2)).shape)

[0 0 0 0 0 0 1 1 1 1 1 1]
(12,)
[[0 0 0 0 0 0]
 [1 1 1 1 1 1]]
(2, 6)


# Funciones matemáticas
- Aplicar operaciones entre escalares y arrays o entre arrays

In [ ]:
# listas y escalares
lista = [0, 1, 2, 3]
lista *= 3
print(lista)

lista += [1]  # += con listas extiende la lista original, como si usaras .extend()
print(lista)

[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]
[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 1]


In [ ]:
# ndarray hace las operaciones sobre los elementos
array = np.ones((4,), dtype=np.int64)
print(array)
array *= 2
print(array)

array += 10
print(array)

[1 1 1 1]
[2 2 2 2]
[12 12 12 12]


## Operadores unarios y binarios

| Tipo | Operación | Descripción |
|:---------|:-----|:-----|
| Unario | *abs* | Valor absoluto de cada elemento |
| | *sqrt* | Raíz cuadrada de cada elemento |
| | *exp* | e^x, siendo x cad elemento |
| | *log, log10, log2* | Logaritmos en distintas bases de cada elemento |
| | *sign* | Retorna el signo de cada elemento (-1 para negativo, 0 o 1 para positivo) |
| | *ceil* | Redondea cada elemento por arriba |
| | *floor* | Redondea cada elemento por abajo |
| | *isnan* | Retorna si cada elemento es Nan |
| | *cos, sin, tan* | Operaciones trigonométricas en cada elemento |
| | *arccos, arcsin, arctan* | Inversas de operaciones trigonométricas en cada elemento |
| Binario | *add* | Suma de dos arrays |
| | *substract* | Resta de dos arrays |
| | *multiply* | Multiplicación de dos arrays |
| | *divide* | División de dos arrays |
| | *maximum, minimum* | Retorna el valor máximo/mínimo de cada pareja de elementos |
| | *equal, not_equal* | Retorna la comparación (igual o no igual) de cada pareja de elementos |
| | *greater, greater_equal, less, less_equal* | Retorna la comparación (>, >=, <, <= respectivamente) de cada pareja de elementos |

In [ ]:
# ejemplos de operadores
array = np.arange(5)
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [ ]:
# ejemplos de operadores
array1 = np.arange(4)
array2 = np.array([0, -1, 2, -3])

print(array1)
print(array2)

print(np.greater(array1, array2))  # funcion de comparación a > b
print(np.less(array1, array2))  # a < b

[0 1 2 3]
[ 0 -1  2 -3]
[False  True False  True]
[False False False False]


# Estadística descriptiva
- Importante saber la naturaleza de los datos
- Valores máximos, mínimos, distribución, etc.

| Función | Descripción |
|:---------|:-----|
| *sum(arr)* | Suma de todos los elementos de *arr* |
| *mean(arr)* | Media aritmética de los elementos de *arr* |
| *std(arr)* | Desviación estándar de los elementos de *arr* |
| *cumsum(arr)* | Devuelve array con la suma acumulada de cada elementos con todos los anteriores |
| *cumprod(arr)* | Devuelve array con el producto acumulado de cada elementos con todos los anteriores |
| *min(arr), max(arr)* | Mínimo y máximo de *arr* |
| *any(arr)* | En array de tipo *bool*, retorna *True* si algún elemento es *True* |
| *all(arr)* | En array de tipo *bool*, retorna *True* si todos los elementos son *True* (o <>0 en valores numéricos) |
| *unique(arr)* | Devuelve un array con valores únicos |
| *in1d(arr1, arr2)* | Devuelve un array con bool indicando si cada elemento de *arr1* está en *arr2* |
| *union1d(arr1, arr2)* | Devuelve la unión de ambos arrays |
| *intersect1d(arr1, arr2)* | Devuelve la intersección de ambos arrays |

In [ ]:
# sum != cumsum
array1 = np.arange(9)
print(array1)
print(array1.sum())
print(array1.cumsum())

[0 1 2 3 4 5 6 7 8]
36
[ 0  1  3  6 10 15 21 28 36]


In [ ]:
# any vs all
array1 = np.arange(-8, 2).reshape(2, 5)
print(array1)
print(array1.any())  # any para saber si hay elementos True o valores <> 0
print(array1.all())  # all para saber si TODOS los elementos son True o valores <> 0

[[-8 -7 -6 -5 -4]
 [-3 -2 -1  0  1]]
True
False


In [ ]:
# todas las funciones aceptan parametro 'axis'
# 0 para columnas, 1 para filas, 2 para profundidad...
array1 = np.arange(10).reshape(2, 5)
print(array1)
print(array1.all(axis=0))
print(array1.all(axis=1))
print(array1.all())

[[0 1 2 3 4]
 [5 6 7 8 9]]
[False  True  True  True  True]
[False  True]
False


# Álgebra lineal
- numpy.linalg contiene funciones para álgebra lineal
- dot product, multiplicación de matrices, cálculo del determinante, factorizaciones...


| Función | Descripción |
|:---------|:-----|
| *dot(mat1, mat2)* | Devuelve el producto escalar entre dos arrays. Si son matrices 2D, es equivalente a la multiplicación de ambas |
| *matmul(mat1, mat2)* | Devuelve el producto entre dos matrices |
| *trace(mat1, mat2)* | Suma de las diagonales de ambas matrices |
| *det(mat)* | Devuelve el determinante de la matriz |
| *eig(mat)* | Computa los autovalores y autovectores de la matriz cuadrada *mat* |
| *inv(mat)* | Devuelve la inversa de la matriz |
| *qr(mat)* | Computa la factorización QR de *mat* |
| *solve(A, b)* | Resuelve el sistema lineal de ecuaciones *Ax = b* para *b*, cuando *A* es una matriz cuadrada |
| *transpose(mat)* | Devuelve la transpuesta de la matrix |

In [ ]:
A = np.arange(12).reshape(4, 3)
B = np.arange(6).reshape(3, 2)

print(A)
print(B)

print(np.matmul(A, B))
print(np.dot(A, B))
print(
    A @ B
)  # el operador @ representa la multiplicación de matrices y es equivalente a np.matmul(A, B).

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 1]
 [2 3]
 [4 5]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]


In [ ]:
import numpy.linalg as linalg  ## submodulo que contiene funciones algebraicas como det, inversa, etc
import math

# resolver sistema de ecuaciones
# 3x + 2y + 5z = 12
# x - 3y -z = 2
# 2x -y +12z = 32
# Ax = b --> resolver para x

a = np.array([[3, 2, 5], [1, -3, -1], [2, -1, 12]])
b = np.array([12, 2, 32])

print(a)
print(b)
x, y, z = linalg.solve(a, b)
print(f"x={x} y={y} z={z}")

print(math.isclose(3 * x + 2 * y + 5 * z, 12))
print(math.isclose(x - 3 * y - z, 2))
print(math.isclose(2 * x - y + 12 * z, 32))

[[ 3  2  5]
 [ 1 -3 -1]
 [ 2 -1 12]]
[12  2 32]
x=0.7543859649122807 y=-1.2280701754385965 z=2.43859649122807
True
True
True


In [ ]:
# matriz identidad
I = np.identity(4)
print(I)

A = np.arange(16).reshape(4, 4)
print(A)

print(np.matmul(A, I))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


# Filtrado de datos
- Filtrar y modificar datos numéricos con np.where
- Retorna A o B en función de una condición en una array

In [ ]:
prices = np.array([0.99, 14.49, 19.99, 20.99, 0.49])
mask = prices < 1
print(prices[prices < 1])  # slicing condicional

# # mask con los elementos menores de 1
# mask = np.where(prices < 1, True, False)
# print(mask)
# print(prices[mask])

# prices[mask] = 1.0
# print(prices)

print(np.where(prices < 1, 1.0, prices * 3))

"""np.where es extremadamente útil en situaciones donde necesitas aplicar una operación condicional
 a un array entero sin usar bucles explícitos. Proporciona una manera vectorizada y, por lo tanto,
   más eficiente de hacerlo."""

[0.99 0.49]
[ True False False False  True]


'np.where es extremadamente útil en situaciones donde necesitas aplicar una operación condicional\n a un array entero sin usar bucles explícitos. Proporciona una manera vectorizada y, por lo tanto,\n   más eficiente de hacerlo.'

In [ ]:
# Se puede usar para sustituir datos fuera de rango
bank_transfers_values = np.array([0.99, -1.49, 19.99, 20.99, -0.49, 12.1]).reshape(2, 3)
print(bank_transfers_values)
clean_data = np.where(bank_transfers_values > 0, bank_transfers_values, 0)
print(clean_data)

[[ 0.99 -1.49 19.99]
 [20.99 -0.49 12.1 ]]
[[ 0.99  0.   19.99]
 [20.99  0.   12.1 ]]


In [ ]:
# limpiar NaN (sustitución)
data = [10, 12, -143, np.nan, 1, -3]  # np.nan --> NotANumber, elemento especial

np.any(np.isnan(data))

True

In [ ]:
data_clean = np.where(np.isnan(data), 0, data)
print(data_clean)

[  10.   12. -143.    0.    1.   -3.]


In [ ]:
# np.where puede seleccionar elementos
bank_transfers_values = np.array([0.99, -1.49, 19.99, 20.99, -0.49, 12.1]).reshape(2, 3)
print(bank_transfers_values)
credits = np.where(
    bank_transfers_values > 0
)  # array de índices para los que la condición es True

print(credits)
print(
    bank_transfers_values[credits]
)  # es igual que bank_transfers_values[bank_transfers_values > 0]
print(bank_transfers_values[bank_transfers_values > 0])

[[ 0.99 -1.49 19.99]
 [20.99 -0.49 12.1 ]]
(array([0, 0, 1, 1]), array([0, 2, 0, 2]))
[ 0.99 19.99 20.99 12.1 ]
[ 0.99 19.99 20.99 12.1 ]


# Números aleatorios
- Python módulo random

In [ ]:
import random

print(
    random.random()
)  # genera numeoros float entre 0 y 1 (excluyendo 1, [0,1)) (uniforme continua)
print(
    random.randint(0, 5)
)  # genera un numero entero aleatorio en el rango[0,5] (uniforme discreta)
print(
    random.uniform(0, 5)
)  # genera numero float entre 0 y 5 (incluye ambos extremos) (uniforme continua)

0.591051298583392
0
0.5875369713894851


In [ ]:
# elegir un elemento al azar dentro de una colección
names = ["Pikachu", "Eevee", "Charmander"]
random.choice(names)

'Pikachu'

## NumPy.random
- Generar fácilmente listas con valores aleatorios

In [ ]:
print(
    np.random.rand()
)  # genera número aleatorios entre 0 y 1 (equivalente random.random)
print(np.random.randint(0, 5))  # integral entre dos valores
print(
    np.random.randint(5, size=(2, 4))
)  # parametro 'size' para indicar las dimensiones)

0.3370396082431356
3
[[0 0 1 4]
 [0 2 3 2]]


In [ ]:
# array de elementos aleatorios (distribucion normal gaussiana, media 0, desviación 1)
print(np.random.randn(4, 2))

[[ 0.09500366 -0.12969959]
 [ 2.28982919  0.63632914]
 [ 1.28351153  0.00653193]
 [-2.55417713 -0.46438539]]


In [ ]:
# otras distribuciones
print(np.random.binomial(n=5, p=0.3))  # 'n' intentos, 'p' probabilidad
print(np.random.uniform(low=0, high=10))  # distribución uniforme
print(
    np.random.poisson(lam=2, size=(2, 2))
)  # 'lam' número de ocurrencias esperadas, retornar 'size' valores

1
9.589624005717612
[[2 2]
 [2 3]]


## Random seed
- Números pseudo-aleatorios
- Ordenadores generan números a partir de ecuaciones
- Basadas en un número inicial (seed)
- Bueno para reproducibilidad de experimentos

In [ ]:
i = 5
for _ in range(5):
    np.random.seed(
        i
    )  # misma semilla :: al fijar la semilla se repiten los valores aleatorios.
    print(np.random.rand())
    print(np.random.rand())

print()

for i in range(6):
    np.random.seed(i)  # diferentes semillas ::  valores generados son diferentes.
    print(np.random.rand())
    print(np.random.rand())

0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764

0.5488135039273248
0.7151893663724195
0.417022004702574
0.7203244934421581
0.43599490214200376
0.025926231827891333
0.5507979025745755
0.7081478226181048
0.9670298390136767
0.5472322491757223
0.22199317108973948
0.8707323061773764
